apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-02-28T10:22:24Z
  generation: 2
  labels:
    app: bahamut
  name: bahamut
  namespace: default
  resourceVersion: "618063"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bahamut
  uid: bda982b2-3b42-11e9-9dac-42010aa0019e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bahamut
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bahamut
    spec:
      containers:
      - env:
        - name: gryffin
          valueFrom:
            configMapKeyRef:
              key: gryffin
              name: bahamut-config
        image: asia.gcr.io/gryffindor-1550651944789/appengine/default.20190228t170052:latest
        imagePullPolicy: Always
        name: default-20190228t170052
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-28T10:23:09Z
    lastUpdateTime: 2019-02-28T10:23:09Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
